KMS UPDATE: non hardware based operations
openwallet-foundation/architecture-sig pull request #52
Opened 2023-08-21 12:35 UTC by ehanoc

# What

- Issues when no hardware support is available for cryptographic / kms operations
- Isolation strategies
- Run-time environments security risks
- Mitigating risks with app / kms designs

2023-09-10 20:18 UTC, c00kiemon5ter requested changes
Minor formatting/whitespace changes.

In general, I like this.

2023-09-10 20:18 UTC, c00kiemon5ter commented on docs/architecture/key-management-services.md
> +    - Besides the traditional NIST crypto; Apple has native support for Curve25519,EdDSA, ECDH, xchacha20 symmetric encryption scheme
```suggestion
    - Besides the traditional NIST crypto; Apple has native support for Curve25519, EdDSA, ECDH, xchacha20 symmetric encryption scheme
```

2023-09-10 20:18 UTC, c00kiemon5ter commented on docs/architecture/key-management-services.md
> +                    ComponentDb(kmsDb, "keyStorage", "Database","Encrypted Keystore")
```suggestion
                    ComponentDb(kmsDb, "keyStorage", "Database", "Encrypted Keystore")
```

2023-09-10 20:18 UTC, c00kiemon5ter commented on docs/architecture/key-management-services.md
> +                Component(hsm, "HSM", "HSM","Hardware Security Module")
```suggestion
                Component(tee, "TEE", "TEE", "Trusted Execution Environment")
                Component(hsm, "HSM", "HSM", "Hardware Security Module")
```

2023-09-10 20:20 UTC, c00kiemon5ter commented on docs/architecture/key-management-services.md
> +    - etc
I am sure we are not the first to propose such a separation.
Can we have examples of other systems working this way?
Can we learn from their experience?
Can we study and reuse their APIs?

2023-09-25 16:33 UTC, tkuhrt commented on docs/architecture/key-management-services.md
> +Given that a wallet maybe be deployed or installed in a OS or environment that does not have hardware available that can provide all the cryptographic operations needed, we need to consider a non-har
```suggestion
Given that a wallet may be deployed or installed in a OS or environment that does not have hardware available that can provide all the cryptographic operations needed, we need to consider a non-hardware mode of operation.
```

2023-09-25 16:35 UTC, tkuhrt commented on docs/architecture/key-management-services.md
> +Non compliant with some security industry standards and regulations where separation of duties is a must
```suggestion
- Non compliant with some security industry standards and regulations where separation of duties is a must
```

2023-09-25 16:36 UTC, merged